### ISSUE TITLE
Семантические тэги

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#10]
Они в проекте не используются абсолютно.

**Comment by performanceArtist** [comment]
Если ты про html5, то мне кажется, что они тут не нужны особо. Разве что можно article или section поставить, а так тут ни футера, ни хедера, ни навигации нет. Это обязательно?

**Comment by performanceArtist** [comment]
Конечно, можно header для заголовков у резюме использовать, но тогда класс для него нужно будет оставить(ведь нельзя использовать для стилизации по БЭМ просто элементы), в итоге получится то же самое фактически.

**Comment by Sergio-Ka** [comment]
> Это обязательно?

Это обязательно. Да у тебя тут нет header, footer, но как ты верно заметил можно использовать article и section. Семантичная верстка - наше всё и стандарт де-факто на сегодняшний день.

**Comment by Sergio-Ka** [comment]
Тот же абзац (<p>) в профайле кстати.

**Comment by performanceArtist** [comment]
>Тот же абзац

То есть p? Можно сделать, но у него в браузерах прибавляются отступы - разве это желаемо, если нужно делать ближе к макету?

**Comment by Sergio-Ka** [comment]
Да, `<p>`. На счет отступов проблем вообще не вижу и вопрос звучит странно. У тебя там класс - что тебе мешает сделать как надо отступы в нем?

**Comment by performanceArtist** [comment]
Сделал. В принципе ничего не мешает, но нужно сбросить/перегрузить margin, так как в браузерах у p он по умолчанию есть, в отличие от div.

**Comment by Sergio-Ka** [comment]
Семантика важнее. Можешь закрыть это issue.
