### ISSUE TITLE
Именование переменных

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#11]
Оно должно быть осмысленным не должно быть переменных `n`, `val`

**Comment by performanceArtist** [comment]
В случаях с обычой for-итерацией непонятно как именовать(хотя в js можно чаще всего без неё). Как правило i или n ставится, т.к. смысл сложно найти. Ну пусть будет не n, а counter.

**Comment by Sergio-Ka** [comment]
Тут вообще бы сесть хорошо подумать на тему именований не только переменных, но вообще всяких сущностей и файлов. Нужны емкие короткие названия, не слишком завязанные на внешний вид, такие чтобы было понятно что это. Вот например взять circle-bar. Вот я убрал всего одно css правило и это уже не circle-bar, а какой-то square-bar
![image](https://user-images.githubusercontent.com/33621369/57850212-96b41800-7807-11e9-97ac-f1cb7fc47ad9.png)
&__dot  тот же в circle-bar. Может лучше будет &__scale-item какой-нибудь к примеру.
Блок title - что за title, почему title? Слишком общее название. Какой-нибудь block-title был бы конкретнее.
info тот же. Что за инфо, о чем инфо, почему? Ну и так далее касательно в том числе и переменные типа val, value, всякие инкременты. Посмотри еще раз основательно на предмет обнаружения таких названий. Представь, что ты новый человек пришедший на проект, а там названия типа info или title и ты долго вынужден вникать то ли это title страницы, то ли еще чего-то и что за info такое.

**Comment by Sha1fei** [comment]
Думаю title и info здесь вполне можно оставить. Основной посыл заключается вот в чем, есть некоторые сущности именование которых, либо сильно размыто, либо не совсем верно.
Вот список того. что явно бросается в глаза: 

- .bar => software-range (в блоке bar сомнительно располагать текст )

- .circle-bar  => skill-range (см. выше )

- counter => circle, total =>  circles, checked =>  checkedCircle (тут особо заметна разница с в именованиях, к тому же у тебя не должно быть два состояние checked и unchecked, круг либо выбран checked, либо просто круг без модификатора  )

- each object in objects  =>  each experience in experiences (см. во всех блоках)

**Comment by performanceArtist** [comment]
Так, я уже не знаю, по каким рекомендациям и как исправлять. По порядку:
>.bar => software-range

Если так сделать, то название блока будет описывать принадлежность к родителю. А содержанием может быть что угодно, не только название софта. Для переиспользования блока название не подходит. И software-range может читаться как range, принадлежащее software - не сказал бы, что наличие текста очевидно. 
>circle, checkedCircle

Выше замечание о том, что смысл легко меняется, если убрать одно правило. Значит никаких circle.
>each object in objects => each experience in experiences (см. во всех блоках)

Во всех так не выйдет - education => education(s?) - звучит странно, спорно в плане грамматики. Software - неисчисляемое. Можно сделать softwareObjects - softwareObject, но выглядит не очень. 

>info здесь вполне можно оставить

Так оставить или нет? issue твоё - значит слушать тебя или как?

**Comment by Sha1fei** [comment]
1.  Каким образом .bar => software-range описывает принадлежность к родителю? То что у них схожее именование, ничего не значит, это абсолютно разные блоки. 
2. circle, checkedCircle - это не именование классов тэгов, а именование твоих переменных  в skills. 
3. Прояви фантазию - это творческая часть, у слов полно синонимов (к примеру можно заюзать program вместо software). Переменные должны отображать сущности с которыми ты оперируешь, а не быть object, value, и т.д. 
4. info оставляй

**Comment by performanceArtist** [comment]
>Каким образом .bar => software-range описывает принадлежность к родителю?

Я имею в виду, он описывает сам контент - то есть название софта, хотя там может быть и другое - тот же уровень навыка. Придумал альтернативное название - split-range, а элементы просто как split-range__item. Такое как?

**Comment by Sha1fei** [comment]
Я писал в рамках твоего проекта) Но если ты ведешь к возможности переиспользования своего блока, то ту придется вводить уточнения, как писал выше @Sergio-Ka у тебя для range  может быть использоваться и круги, и квадраты, и т.д. Поэтому тебе придется уточнять именование твоего блока split-range, к тому же item тут уже не подойдет, нужно конкретно указывать что является элементом ренжа, чтобы переиспользовать этот блок внутри  других блоков, где для ренжа используются круги к примеру.

**Comment by performanceArtist** [comment]
Почему нужно уточнять название самого блока? Смысл такой, что это "разделённый" range. А как отображаются части, на который он разбит(которые логично назвать просто item) - уже другой вопрос. Сделал модификатор для круга, который можно задать в миксине через параметр shape, то есть теперь класс для круга выглядит как `split-range__item split-range__item_circle`.

**Comment by Sha1fei** [comment]
Да использование модификатора для itemа тоже подойдет такое решение.
