### ISSUE TITLE
margin, padding у блоков

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#12]
У блоков не должный быть  margin, padding. Завести под каждый блок свой стилевой файл.

**Comment by performanceArtist** [comment]
Почему? Это же регуляция размеров блока/отступов внутри него. Если нельзя их задавать, то как его переиспользовать? Писать стили каждый раз в родительском? Смысл, если можно точно так же из родителя перебить имеющиеся?
>Завести под каждый блок свой стилевой файл.

Так же и сделано.

**Comment by Sergio-Ka** [comment]
Потому что margin - это значит что блок влияет на свое окружение, а он не должен влиять на свое окружение. Ты когда его переиспользуешь из одного места в другое, тебе придется задавать при таком подходе каждый раз разные отступы для разных ситуаций, чтобы отпозиционировать блок. Это ад. Позиционирование должно делаться через обертку. Обертка - это элемент внешнего родительского блока (по БЭМ). На него и вешается позиционирование. padding тут по факту так же работает, только изнутри, потому та же ерунда. В общем случае padding у блока можно использовать, если это часть внешнего вида блока, а не попытка отпозиционировать его или его содержимое. Это значит, что ты если переносишь блок из одного места в другое, то padding не меняешь. Тогда можно. Margin всегда нет.

**Comment by performanceArtist** [comment]
>В общем случае padding у блока можно использовать, если это часть внешнего вида блока

Ну да, я так и понял. Здесь это фиксированный отступ от нижнего текста, задающий размер/вид именно блока, а не отступы от окружения.

**Comment by performanceArtist** [comment]
То есть я отступы задаю только непосредственно в частях резюме(обёртки по сути). Они не должны меняться, чтобы соответствовать макету. Или речь о том, что мне нужно создать элемент-обёртку внутри например блока контакт и туда перенести стили?

**Comment by Sergio-Ka** [comment]
Что значит в частях резюме (которые "обертки по сути")? Если ты говоришь о блоках типа software, profile, skills и т.д. то тогда лучше еще раз изучить теорию БЭМ. Вот здесь, например:
```css
.education {
  padding-bottom: 2%;

  .title {
    margin-bottom: 3%;
  }

  .info {
    margin-right: 5%;
    margin-bottom: 1.8%;

    &__name {
      color: $blue;
    }
  }
}
```
ты фактически задаешь независимым блокам title и info влияние на свое окружение через margin'ы. Ну и потом, это что за запись? Я так понимаю каскады, которые в БЭМ не используются?

**Comment by performanceArtist** [comment]
Сделал с миксами. Теперь все отступы задаются через них (education__section-title), например.

**Comment by Sha1fei** [comment]
Здесь лучше задать отступы на элементах, какие тебе необходимы, и не использовать миксы. 
К примеру у тебя был блок contact, в который вложен блок titlte. У них обоих не должно быть padding. НО допустимо создать например в contact элемент contact__wrapper с помощью которого оттеснить на необходимый отступ сверху и с боков весь внутренний контент. Аналогичный подход можно применить ко всем блокам. Бывают ситуации когда отдельно стоящий элемент смещен относительно других элементов, в этом случае применяем на нем дополнительные отступы.

Почему не нужно использовать миксы:

- Нарушается принцип инкапсуляции - внешний мир лезет в довольно интимную область компонента и должен знать, как там устроены стили, чтобы грамотно их модернизировать и переписывать, плюс как в примере промо страница вдруг начинает содержать стили хедера, хотя она не должна вообще про хедер знать толком

- Если есть 20 использований компонента на 20 разных страницах, нам после изменения одного свойства в компоненте самом придется ВСЕ 20 страниц вручную тестировать, потому что неизвестно какие могут быть стили навешаны в местах использования через кастомные классы и надо самому проверить все комбинации.

- Примесь обычно вешается только на верхний уровень компонента, но иногда надо кастомизировать что нибудь внутреннее, тогда получается, надо уже две примеси передавать и принимать в компоненте, одна примесь для свойств всего блока, второй для какого-то элемента, а когда понадобится еще другой элемент кастомизировать, придется добавить третью примесь :)

- Не получится четко составить список всех возможных состояний компоненты, а при подходе с модификаторами мы явно видим все возможные параметры на входе и когда их число будет зашкаливать, можем пнуть дизайнера, что он слишком расфантазировался и пора бы к единому стайлгайду переходить.

**Comment by performanceArtist** [comment]
Ок, сделал через элементы.

**Comment by Sha1fei** [comment]
У блоков так и остались паддинги.

**Comment by performanceArtist** [comment]
Добавил элементы для отступов, у блоков теперь их нет.

**Comment by Sha1fei** [comment]
![Снимок экрана от 2019-05-24 11-03-25](https://user-images.githubusercontent.com/31854808/58302136-af2dbf00-7e13-11e9-8b24-c7b5a6a5c8ae.png)
Проверяй пожалуйста свой проект более тщательнее.
