### ISSUE TITLE
Блок контакт

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#15]
Если у поля есть четкое назначение, то использовать соответствующий тип (email, number, color и тд)
Для телефонов, емайл-адресов и скайп никнеймов нужно использовать <a> c соответствующим адресом
```
<a href="tel: +74951234567">+7 (495) 123-45-67</a>
<a href="mailto: example@mail.ru">example@mail.ru</a>
<a href="skype: someskype?call">someskype</a>
```

**Comment by performanceArtist** [comment]
Не тот номер, это фикс для шрифтов.

**Comment by Sergio-Ka** [comment]
Можешь закрыть это issue.

**Comment by performanceArtist** [comment]
Поля исправлены.
