### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#16]
Посмотри правила именования шрифтов в стандартах, задание запасного шрифта, задай их в одном месте в главном стилевом файле.

**Comment by performanceArtist** [comment]
По не вполне понятной причине(конвенции?) после переноса на github pages меняются названия шрифтов(конкретно arialmt меняется на ARIALMT, в итоге он не загружается). Возможно, придётся поменять обратно.

**Comment by Sergio-Ka** [comment]
Тут еще замечание до кучи, что у тебя шрифты arialmt заглавными буквами названы, при стягивании проекта возникают ошибки при сборке. Если у тебя в локальном репозитории шрифты переименованы маленькими строчными буквами, то тогда проблема в git, он по умолчанию регистронезависимые настройки имеет. Погугли как исправить. Потом не забудь удалить шрифты прописными буквами названные.
![image](https://user-images.githubusercontent.com/33621369/57844398-2d79d800-77fa-11e9-9ee5-0f5f9aac49e8.png)

**Comment by performanceArtist** [comment]
Да, видел эту проблему. Сейчас поправил.
