### ISSUE TITLE
Папка partials

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#17]
Не вижу смысла в этой папке.
1. Файл _layout.scss содержит стили для body. Его содержимое перенести в main.scss. Импорты в нем все равно исчезнут, когда реализуешь issue #9.
2. _component.scss является частью реализации блока circle-bar и должно быть в его папке. Если предусматривается возможность переиспользования самого блока circle (и соотвественно его выделения как блока), то сделай это по БЭМ - папка в circle в папке components, и уже там все его реализации. А уже он подключается как компонент в circle-bar.
3. _defaults.scss его содержимое должно быть на уровне с index.pug, возможно даже в main.scss, хотя думаю можно и в отдельном файле оставить.

**Comment by performanceArtist** [comment]
Тут всё не так просто выходит. Дело в том, что импорты в js не позволяют использовать переменные и миксины scss. Чтобы они работали, надо их импортировать непосредственно в scss-файлах. Если здесь это может не такая большая проблема, то во втором проекте мне была просто необходима эта папка(partials), чтобы из неё доставать миксины и глобальные переменные. В этом проекте миксин(circle) просто нужен чтобы не повторять часть кода для создания круга(и использовать один рабочий вариант), он не может быть самостоятельным блоком. Во втором задании я делал уже миксины для генерации более сложного css.  Например: есть кнопка arrow-button. Я захотел на какой-то странице или в элементе сделать её поменьше. Я просто подключаю файл с миксинами и пишу: 
```scss
.blockname { 
  .arrow-button { 
    @include set-arrow-button-size(2rem);
  }
}
```
И соответственно размер самой стрелки высчитывается относительно размера круга. При этом я не могу держать миксины в том же файле стилей блока, потому что если его где-то подключить, из него посыплются лишние стили(оттуда и выделение папки partials, потому что файлы там не компилируются). Конечно, есть ещё вариант положить в каждый блок отдельный файл с миксинами, но с одним файлом проще(меньше указаний путей и прочего - с несколькими страницами можно разом подключить все миксины и переменные парой импортов).

**Comment by performanceArtist** [comment]
Всё-таки нашёл решение проблемы и применил во втором задании - в webpack можно везде подключить глобальный scss файл. При этом так как это partial, размеры не увеличатся, зато можно будет где угодно использовать миксины и переменные без лишних импортов.

**Comment by performanceArtist** [comment]
Здесь тоже так сделал, по-моему неплохое решение. Сразу ясно, где находятся общие переменные и импортировать ничего не надо.

**Comment by Sergio-Ka** [comment]
В общем в данном случае идея с миксином в файле globals.scss не самая лучшая. 
@mixin circle($size, $outer-color) {
  margin: auto;
  border-radius: 50%;
  overflow: hidden;
  box-shadow: 0 0 0 0.0625rem $outer-color;
  box-sizing: border-box;
  height: $size;
  //sort of a hack, but works in Firefox/Chrome
  min-width: $size;
  max-width: $size;
}
Первое свойство только для блока avatar для заголовков блоков не нужно, значит нужно перенести его в реализацию для avatar. То же для overflow. box-sizing можно навешать на универсальный селектор *. Хак с шириной пользовать плохая идея для общего миксина. Тем более он влияет только на отображение мелких иконок, а значит уже часть реализации блока для мелких иконок. По итогу общих свойств у тебя только border-radius и box-shadow. И вообще в стандартах есть про самодостаточность компонентов и пояснение в части про CSS БЭМ. Почитай. Получается ты не сам компонент переиспользуешь, а выделяешь общую часть реализации по сути в разных блоках, и тянешь его на верх по структуре, добавляешь не нужные зависимости. В данном случае нужно прибрать этот миксин, разнести его по блокам. Константы цветовые и шрифтовые лучше перенести в main.scss.

**Comment by performanceArtist** [comment]
>Константы цветовые и шрифтовые лучше перенести в main.scss.

Тогда никакие больше файлы кроме main.scss их не увидят, как я писал выше.

**Comment by Sergio-Ka** [comment]
Ну ОК, оставь тогда так. Это issue можно закрыть.
