### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#18]
Разделить зависимости необходимые для devDependencies и dependencies
https://www.reddit.com/r/node/comments/1nticr/whats_the_difference_between_dependencies_and/

**Comment by performanceArtist** [comment]
Но в этом случае ведь ничего на сервер устанавливать не нужно, в отличие от зависимости вроде express, например. Получается они все dev. Всё в итоге перегонится в html/js/css без всяких зависимостей. Даже по ссылке:
>When you deploy your app, modules in dependencies need to be installed or your app won't work.

А здесь установка не требуется.

**Comment by Sha1fei** [comment]
У тебя браузер умеет читать css js html, код написанный  на pug, scss он не сможет прочитать 
 для транспиляции используешь лоадеры, да и собирается все воедино через webpack.

**Comment by performanceArtist** [comment]
Но рендерится это не на стороне сервера ведь. Мне не нужно ставить на сервер webpack или его загрузчики, я об этом. Туда переносится только результат сборки. Если бы там шаблоны pug собирались и отправлялись, я бы понял. У node ведь в зависимости ставится то, что нужно установить и использовать на сервере - express там, всякие парсеры и прочее.

**Comment by Sha1fei** [comment]
Ты не на то обратил внимание, для сборки твоего приложения тебе нужны зависимости без которых твое приложение банально не получится собрать (dependencies). А есть зависимости  которые требуются исключительно для разработки (devDependencies),  к примеру eslint, и без них собрать проект тебе ничего не помешает. Где же ты решишь произвести сборку прод не имеет значения.

**Comment by performanceArtist** [comment]
Хорошо, пусть тогда в зависимостях будут зависимости сборки. С точки зрения node несколько странно, но в принципе роли при сборке не сыграет.

**Comment by Sha1fei** [comment]
А как ты без вебпака планируешь собирать прод?)

**Comment by performanceArtist** [comment]
Но ведь эти зависимости они и есть для сборки/webpack-а, нет? Тогда они в разных категориях.

**Comment by Sha1fei** [comment]
Для сборки тебе необходим webpack, а без webpack-dev-server и  webpack-cli, ты вполне можешь обойтись Поэтому пусть останутся в devDependencies. Как подправишь можешь закрывать ишью.
