### ISSUE TITLE
Еще раз отверить проект по стандартам FSD

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#2]
так было замечено следующее
- использование id, селекторы должны быть по классам
- отрицательные margin
- единицы измерения должны быть rem (допустимо % при задании пропорций) вместо всяких pt px и прочего
- форматирование css (отступ в 2 пробела)
это при поверхностном взгляде. Подозреваю что есть еще.

**Comment by performanceArtist** [comment]
А что где допустимо использовать? Можно применять пиксели для медиа-запросов или максимальной ширины картинки, например? Пойдёт, если я для текста буду использовать rem/em, для задания отступов проценты или em в тех случаях, когда это логично(отступы для текстовых элементов)?

**Comment by Sergio-Ka** [comment]
Только rem, не em. Надо еще разок наверное стандарты глянуть? Для медиа-запросов да, можно в px оставить. Максимальной ширины картинки думаю нет. Да тут и нет таких кейсов в этом проекте, чтобы в пикселях там что-то задавать. И где там какие картинки что настолько большие чтобы им передавать максимальный размер? Либо rem либо  % - это из практики для первого проекта. Можно обойтись только ими здесь.

**Comment by performanceArtist** [comment]
Я в общем спросил, тут понятно что максимальной ширины картинок нет - это во втором задании мне нужно. em мне кажется логичным использовать в составных блоках - например задал для всего блока значение в rem, а внутри уже используешь em. Хотя по сути можно и без em обойтись, с наследованием может усложниться.

**Comment by Sergio-Ka** [comment]
Если в процессе развития проекта тебе понадобиться обернуть внутренний блок еще в десяток блоков, у которых будут заданы свои размеры? Тебе надо будет лезть в этот блок и менять его размер в `em` на другое значение, чтобы размер соответствовал. Будешь тратить время.
Ну, я тут не свои хотелки увы высказываю. Есть принятые стандарты. Они не просто так появились. Бывают отступления на практике. Но это всегда нужно очень четко понимать, что ты делаешь и чем это может обернуться в будущем. Что до этого ишью. Пусть пока висит. Я буду смотреть соответствия всем стандартам, коих много и вопрос не сильно быстрый.

**Comment by Sergio-Ka** [comment]
1. У каждой страницы должны быть теги title и мета теги keywords, description. Содержимое придумать самому в этом случае. Вообще уточняется у менеджера проекта.

**Comment by Sergio-Ka** [comment]
2. Блоки проверить на переполнение, в частности:
![Снимок](https://user-images.githubusercontent.com/33621369/57440871-fbed9380-7272-11e9-81b1-e2e399655b89.PNG)
3. !Все изображения должны содержать alt. У аватара я такого атрибута не заметил.
4. Ссылки на чужие сайты должны содержать атрибут target="_blank", чтобы открываться в новом окне. Не заметил такого атрибута у ссылки в контактах.
5. Все ссылки с target="_blank" должны так же содержать атрибут rel="noopener noreferrer", это связано с уязвимостью. Этот пункт - следствие четвертого.
6. Подключаемые файлы
!Все картинки, шрифты и тд должны иметь уникальное название в рамках проекта и не содержать кириллических символов. Если в проекте нет индивидуальных соглашений, то они должны именоваться в стиле lower-case-hyphenated. Шрифты отыменованы как скачаны. На мой взгляд и в favicons не совсем все гладко. Опять же файл _globals.scss явно назван не по стандартам.

По HTML пока все.

**Comment by performanceArtist** [comment]
А как именно нужно исправлять переполнение? Я могу сделать перенос слов, но он изуродует текст.

**Comment by Sergio-Ka** [comment]
CSS:
7. !Прописывать дефолтный цвет фона, цвет шрифта, font-size и семейство шрифта у html
8. !Слова, целиком состоящие из верхнего регистра, предпочтительно делать через стиль text-transform: uppercase, а не реальным вводом текста заглавными буквами. Везде неписаны в ручную прописными буквами.
9. !На элементах без специфичных требований (не фиксированные пиксели и не относительно области экрана) использовать rem. Вижу line-height безразмерные. Это значит что данный размер задающий высоту строк будет зависеть от размера шрифта, а значит и элементы содержащие строки будут зависеть от того же. А если скажем надо будет чуть увеличить или уменьшить высоту шрифта, но так чтобы ничего не поплыло?

Пока по CSS тоже все. Может потом добавится еще что-то.

**Comment by Sergio-Ka** [comment]
> А как именно нужно исправлять переполнение? Я могу сделать перенос слов, но он изуродует текст.

Ну изуродует. Из двух зол лучше выбрать меньшее. Лучше будет если длинное имя будет наползать на соседнюю колонку?

**Comment by performanceArtist** [comment]
Про регистр вспомнил сам, поэтому коммит с исправлением его был раньше.

**Comment by performanceArtist** [comment]
>Если в проекте нет индивидуальных соглашений, то они должны именоваться в стиле lower-case-hyphenated

С этим появилась проблема: отписал в #16.

**Comment by Sergio-Ka** [comment]
Тут пока прикрою, так как перечисленные пункты выполнены. Возможно еще будут вопросы по оптимизации свойств css (возможно дублирование или лишние css свойства) и по позиционированию блоков. Хотя последний возможно в рамках issue #12 решится.
