### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#20]
Объедини options и info переменные и передавай их в миксин

**Comment by performanceArtist** [comment]
Тогда весь смысл блока потеряется, т.к. передать можно будет что угодно и каждый раз придётся писать вещи вроде `rel:'noopener noreferrer'`. И получатся не "контакты", а просто какой-то набор ссылок. Могу конечно сделать, но стоит ли?

**Comment by Sha1fei** [comment]
Какой смысл потеряется? Тебе для того чтобы срендерить строку блока контакт нужны параметры для каждой их них, вот и передавай объектом параметры, а если чего то нет то и вставлять ничего в mixin не нужно.

**Comment by performanceArtist** [comment]
И мне тогда дублировать параметры по умолчанию что ли? Обсуждали с другим проверяющим, что нужно для каждого миксина сделать минимальные значения даже без передачи чего-либо - в этом случае это четыре ссылки address-email-phone-website.

**Comment by Sergio-Ka** [comment]
По умолчанию у тебя может быть одна строка в данном случае для всего блока, например, address - для случая когда ты передаешь пустой объект или какую-нибудь ерунду на вход.

**Comment by performanceArtist** [comment]
Сделал так, чтобы когда ничего не передавалось был просто адрес. Передаётся объект и проверяются имена address, email и так далее. По-моему и так было нормально - передавать нужно было меньше, было больше функционала с аргументами по умолчанию и вообще было чище, чем сейчас, когда можно туда что угодно накидать.
