### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#21]
При разметки в 320 px видно что контент скиллs и контакт не отцентрирован и смотрится криво. Так же  контент в software на мобильных версиях стоит разместить в две колонки а не в одну.
![Снимок экрана от 2019-05-24 12-09-12](https://user-images.githubusercontent.com/31854808/58304125-3cc1dc80-7e1d-11e9-9ca1-1c33056fc79a.png)
![Снимок экрана от 2019-05-24 12-09-39](https://user-images.githubusercontent.com/31854808/58304129-3f243680-7e1d-11e9-95d1-8e8317f3d129.png)

**Comment by performanceArtist** [comment]
Skills раньше было центрировано, при изменениях случайно убрал - сейчас поправил. Contact на макете будто не центрировано - добавил отступ для меньших размеров, чтобы лучше смотрелось. И разве контент software и так не в две колонки? Или речь о непосредственно элементах колонок?

**Comment by Sha1fei** [comment]
Не то написал, лучше сделать в одну колонку а не в две)

**Comment by Sha1fei** [comment]
Как подправишь можешь закрывать ишью

**Comment by performanceArtist** [comment]
Сделал для маленьких размеров экрана, до переноса after effects.
