### ISSUE TITLE
wrapper

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#22]
Для задания отступов обычно использую элемент wrapper, контент тоже подойдет, но у тебя где то контент, где то хедер, что точно не подходит для именования элемента. Приведи к единому виду плиз.

**Comment by performanceArtist** [comment]
Почему не подходит? header - это заголовок, а далее контент. Разделены, т.к. мне нужно задать разные отступы между ними, а также в паре мест отступы слева для контента, но не для загловка. Везде одинаково. wrapper это скорее для всего, включая хедер.

**Comment by Sha1fei** [comment]
Да, тут с именованием согласен, это я пропустил что у тебя имеются оба элемента внутри блока.  Хотя здесь вполне можно было обойтись без header, задать нужные отступы на элементах, section-title, и и использовать к примеру content элемент для отступа между блоками.
