### ISSUE TITLE
Проценты

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#23]
В требованиях есть такой пункт. На элементах без специфичных требований (не фиксированные пиксели и не относительно области экрана) использовать rem. У тебя на элементах в маржинах и паддингах используются % замени их на rem.

**Comment by performanceArtist** [comment]
Где-то было о том, что проценты тоже допустимы. Но ладно, не буду спорить. Исправил - теперь немного дальше от макета(проценты задавали изменяющиеся отступы, и к нему почему-то было ближе), но вид основной сохранился. Сразу упомяну, что в основном блоке(resume) проценты оставил, т.к. там задаётся положение относительно экрана. В software тоже оставил оступ справа в процентах, так как он должен меняться, чтобы полоски были центрированы.
