### ISSUE TITLE
БЭМ et al

### ISSUE THREAD

**Issue by alextsk** [performanceArtist/resume_template#24]
profile__crucial-info - немного изменяет отображение, может будет лучше как модификатор?

.education__info .info__name { - блоки не должны влиять на стили вложенных

range__text - основной повод вынести блок - reuse. заголовок точно относится к блоку прогресс-бар?

split-range - то же

education__list, experience__list - в ul лежит div - это не по христиански

contact__info - и тут можно выбрать теги посемантичнее

article.resume  - https://developer.mozilla.org/ru/docs/Web/HTML/Element/article
я не уверен что это article

**Comment by performanceArtist** [comment]
>profile__crucial-info - немного изменяет отображение, может будет лучше как модификатор?

Модификатор чего? По БЭМ отдельно его использовать нельзя. Значит элемент для текста так и так потребуется, а в названии уже указано, что это важная информация и ещё модификатор поверх ставить будет как-то жирно.

>range__text - основной повод вынести блок - reuse. заголовок точно относится к блоку прогресс-бар?

Немного не понял, в чём проблема с заголовком? Его можно и не задавать - будет пустой. Почему бы и не оставить опцию, тем более раз это статичный элемент, в котором мало функционала?

>в ul лежит div - это не по христиански

ul/li ведь блоковые элементы, что тут не так?

>contact__info - и тут можно выбрать теги посемантичнее

Можно поставить section наверное, но что ещё? header не подойдёт, а больше там внутри нет ничего.

>я не уверен что это article

>represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable

Вполне можно это резюме куда-нибудь приложить или использовать в пределах сайта -  к примеру, как обёртку для информации о сотрудниках. Оно же независимо и ни к чему не привязано.

**Comment by alextsk** [comment]
> Модификатор чего?

текста. например есть класс текста .just-text где стили общие для большинства текстовых полей и вариант .just-text.just-text_important с другим начертанием.

> ul/li ведь блоковые элементы, что тут не так

кроме модели отрисовки есть еще семантика, ожидается что в **unordered list**, будет лежать **list item** а див это что?

contact__info - на выбор - ul, dl, table

> Немного не понял, в чём проблема с заголовком?

он часть прогресс бара или часть секции? 
если писать блок с заделом на переиспользование - что проще - постоянно передавать в него пустой заголовок или ставить его когда  он нужен? 
если стилизация заголовков по сайту однотипна, а скорее всего это так - я не могу использовать этот блок? или надо попросить разработчика написать по модификатору для каждой комбинации шрифтов\размеров?

article - да, расплывчатое определение, для меня логичнее что это блоки которые можно переиспользовать внутри сайта, а то так можно выдачу гугла подогнать под артикл, но тут я не настаиваю

**Comment by alextsk** [comment]
style:'education', - если поменялся дизайн, и теперь выделенные заголовки на experience. подходит ли этот стиль?

**Comment by performanceArtist** [comment]
>текста. например есть класс текста .just-text где стили общие для большинства текстовых полей и вариант .just-text.just-text_important с другим начертанием.

Как я говорил, здесь это немного жирно с учётом того, что он нигде больше не используется и содержит по сути одно свойство css. Ну могу сделать блок для текста, если нужно.

>кроме модели отрисовки есть еще семантика, ожидается что в unordered list, будет лежать list item а див это что?

Но эта обёртка всё же нужна для подгонки. По БЭМ нельзя задавать отступы для блока(info, с тегом li). Как вариант, могу убрать вообще ul/li и сделать всё с div.

>если писать блок с заделом на переиспользование - что проще - постоянно передавать в него пустой заголовок или ставить его когда он нужен?

Он по умолчанию стоит как пустой, в объекте можно написать только то, что нужно, так что этой проблемы не возникнет. 

>или надо попросить разработчика написать по модификатору для каждой комбинации шрифтов\размеров?

Можно обернуть его в любой контейнер и там перегрузить css для текста(у меня есть например software__range, в нём можно), всё равно он скорее всего потребуется для позиционирования. Или просто не ставить заголовок в аргументе и сделать новый блок на его основе - в нём уже наворотить что-то ещё, но это уже чересчур. Не понимаю, как выделение заголовка должно что-то упростить - так и так придётся модифицировать.

**Comment by alextsk** [comment]
>  учётом того, что он нигде больше не используется 

как и любой элемент тут, на то оно и учебное задание)

> содержит по сути одно свойство css.

т.е. для модифкатора этого мало а для элемента норм?

> По БЭМ нельзя задавать отступы для блока

это не про бэм, это про смысл тегов. список должен лежать в ul, это правильно, а дети ul всегда li 

> Не понимаю, как выделение заголовка должно что-то упростить - так и так придётся модифицировать.

что модифицировать? элемент используется в разных контекстах и заголовок чаще всего относится к контексту а не к блоку, и в твоем варианте придется прокидывать какие-то стили контекста в элемент, чтоб стилизовать его заголовок, что вообще противоречит бэм. 
тут простой выбор мне кажется

**Comment by alextsk** [comment]
> Ну могу сделать блок для текста, если нужно.

а модификаторы только на блок можно добавлять?

**Comment by performanceArtist** [comment]
Я что-то не пойму, что требуется. Ну вот добавил модификатор, что изменилось? Теперь элемент лишний будто. С остальным вроде понятно - вынес заголовки из range, поправил info, чтобы в ul были только li.

**Comment by alextsk** [comment]
> Ну вот добавил модификатор, что изменилось

здесь ничего. но если понадобится текст с теми же атрибутами но italic, можно будет добавить модификатор. это бэм, смысл его в унификации, ты читаешь код и видишь элемент у тебя немного другие ожидания чем от модификатора

**Comment by alextsk** [comment]
```
.info_education {
  .info__name {
    color: $blue;
```

модификаторы часто нужны чтобы не использовать каскад. бэм не одобряет каскад
почему дженерик блок info знает о каком-то education? т.е. о своем окружении

**Comment by performanceArtist** [comment]
Это просто модификатор стиля по идее, можно и по-другому назвать - не факт, что он привязан к окружению.

**Comment by alextsk** [comment]
ты пишешь блок и используешь его на другом проекте, твой коллега читает код и видит класс education в стилях, вопрос: какая его первая цензурная мысль?

попробую по порядку
дженерик блок здесь - это ожидаемо по макету 
есть два варианта - сделать блоком весь список, или каждый элемент списка, я лично за элемент, но это не так важно
стили блока - одни и те же за исключением окраски заголовка в одном из вариантов - это highlighted, emphasized, bold и тд, но не education

**Comment by performanceArtist** [comment]
Пусть будет другое название тогда, список и так в блоке.

**Comment by performanceArtist** [comment]
Хотя лучше blue_name, а то title там уже есть отдельно.

**Comment by alextsk** [comment]
лучше без цвета, типа "выделенный_заголовок", так можно будет изменить стили не меняя класс
