### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by alextsk** [performanceArtist/resume_template#25]
Компонент должен точно определять свой контракт. Множество классов например должно быть конечным.

li(class = style === '' ? 'info' : `info info_${style}`) - 
например, какие есть возможные значения style? 

не стоит интерполировать значения из ввода напрямую в класс или значение
.range__progress(style='width:' + percentage)
что если передано percentage=1000? что если в конце px?

**Comment by performanceArtist** [comment]
Здесь на усмотрение на разработчика и для простоты так, это всё же не пользовательский инпут. Как ты предлагаешь ограничить значения? В pug ни исключений, ни нормальной типизации нет. Не ставить же везде условия в самом деле.

**Comment by alextsk** [comment]
а что ты планировал типизировать?

с шириной: привести к числу, не  удалось - дефолтный минимимум, удалось но больше максимума - дефолтный максимум

с классами: - хешмап, ключ - параметр, значение - класс. не нашлось параметра в списке - дефолт (или ничего)

**Comment by performanceArtist** [comment]
>а что ты планировал типизировать?

Те же значения процентов, например. А так нужно будет парсить строку.

>с классами: - хешмап, ключ - параметр, значение - класс

Я так не сделал, чтобы условия не городить. Что ж, похоже придётся.

**Comment by alextsk** [comment]
> А так нужно будет парсить строку 

 parseInt?

> чтобы условия не городить

не знаю про что ты, я представляю что то типа valuesMap[param] || "default_class"

**Comment by alextsk** [comment]
> Те же значения процентов, например.

просто из любопыства, как бы ты это типизировал в другом языке?

**Comment by performanceArtist** [comment]
>не знаю про что ты, я представляю что то типа valuesMap[param] || "default_class"

А что тогда будет в самом значении? Полное имя? Придётся повторяться. Ну да ладно, я завтра посмотрю, как лучше сделать.

>просто из любопыства, как бы ты это типизировал в другом языке?

unsigned int например - дальше просто проверить, что он меньше 100.

**Comment by performanceArtist** [comment]
Можно ещё свой тип сделать с "умным" конструктором в Haskell, но это перебор пожалуй.

**Comment by viktoriya-ch** [comment]
Это ишью можно закрывать
