### ISSUE TITLE
Компонентный подход

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#3]
1. Пересмотреть деление страницы на БЭМ блоки. Тут не нужно мельчить слишком. Например, резюме 7 блоков, остальное - элементы. Переиспользуемые элементы так же можно сделать блоками по БЭМ (например, блок с заголовком и рисунком, всякие skill и т.п.)
2. Оформить каждый такой блок миксином в pug, все реализации блоков на каждой из технологий должны лежать в своей папке с названием блока. (типа папка profile в ней файлы html/pug, css/scss, js, рисунки если есть и т.д.). Каждый дочерний компонент подключается в родительском и так далее до самого корня. Эти блоки по БЭМ оформленные в миксинах в своих папках каждый для данного проекта положить на один уровень (не вкладывать друг в друга в структуре папок).

**Comment by performanceArtist** [comment]
То есть надо делить на блоки даже если они не используются несколько раз?

**Comment by performanceArtist** [comment]
В последнем коммите всё поправил - убрал лишние блоки, поменял структуру. Сейчас те блоки, что можно заново использовать, лежат в папке components, а непосредственно части резюме в composite. Можно сразу этот коммит смотреть, т.к. многое поменялось. Иконки оставил как есть, но если принципиально нельзя их использовать, могу заменить на картинки или ещё на что. Но мне кажется просто указание класса более чистым, чем возня с png или svg.

**Comment by Sergio-Ka** [comment]
Ну уже гораздо лучше. Некое подобие компонентного подхода соблюдено. Дальнейшие вопросы в следующих ишью.
