### ISSUE TITLE
Передавать параметры блоков в миксины в виде {объектов}

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#4]
Это позволит в миксинах, используя декомпозицию, сократить имена переменных, так же позволит назначить дефолтные значения. При вызове можно будет передавать параметры в любом порядке и не полностью, при необходимости, тогда будут использоваться заданные дефолтные значения.

**Comment by performanceArtist** [comment]
То есть надо везде объекты использовать? Почему? Я большого смысла не вижу, когда там два параметра и оба обязательные, вроде `+bar('60%', 'PHOTOSHOP')`. Там, где их много и неочевидно, где что, как раз и используются объекты. И как связаны декомпозиция и длина имен?

**Comment by Sergio-Ka** [comment]
Декомпозиция и длина имен связаны так - если ты обращаешься к свойствам объекта, то надо писать типа - <имя объекта>. <имя свойства>. Если ты делаешь декомпозицию по типу:
mixin avatar(options)
    if (!options)
        -options = {name:"name", surname:"surname", occupation:"ocupation"};
    -let {name="name", surname="surname", occupation="occupation"} = options;
то ты потом можешь обращаться к непосредственно переменным без указания имени объекта. Это во-первых короче. Во-вторых сюда же до кучи: использовать сокращение имен типа opt - дурной тон. Это здесь у тебя более менее понятно, а в большом проекте можно долго голову ломать, что это за переменная из трех букв. Учись сразу везде именовать переменные коротко, емко и без сокращений. Это вообще всего касается, не только js.
На счет первого вопроса. Ты пойми, это здесь проект у тебя простой и кажется, что это лишние телодвижения. Но здесь на простом задача научится стоит, потому ты не реальный проект разбираешь, где побыстрее надо сделать, а учишься. От того и черезмерные усложнения. А вообще ты можешь в данном случае получать объект и передавать его дальше в другой миксин, который внутри будет, а там еще миксин и так далее. Каждый раз будешь вручную параметры передавать или просто будешь передавать один и тот же объект, а каждый миксин будет брать только то, что ему конкретно нужно?
На счет +bar() это верно, это у тебя одна и та же функциональность повторяется внутри блока и ее стоит оформить миксином. Только вызывать ты ее должен не внутри блока software, а передавать там где вызываешь миксин этого блока software сразу параметром, весь массив объектов bar. Это в данном проекте у тебя 6 блоков bar. А если 100 будет, будешь параметры каждого вручную прописывать?

**Comment by performanceArtist** [comment]
А, ты про само имя объекта. Просто по идее тогда нужно будет писать сначала назначение переменных, а потом использовать их - в итоге здесь получится примерно одинаковое количество символов. Ну да ладно, понятно.

Про сокращения учту, вообще обычно стараюсь сильно не мельчить, кроме отдельных очевидных случаев.

bar я так и передаю массивом в блок software в новой версии. Внутри уже итерация и вызов миксина для каждого элемента. Можно в bar тоже передавать объект, по сути будет то же самое.

**Comment by Sergio-Ka** [comment]
Ну да в другом ишью отписал частично. Здесь суть декомпозиции - ты делаешь это в одном месте. Потом используешь переменные более короткие. Если будет несколько мест по коду, где будут использоваться они - то экономия в количестве знаков будет на лицо. Кроме того здесь еще до кучи проверяется случай когда например объект в миксин сверху может вообще не передаваться, или будет передаваться пустой объект, тогда будут использоваться значения по умолчанию которые здесь как раз и задаются. Я там вчера не совсем корректно написал, точнее корректно, но можно короче. Код лучше всего так выглядеть будет:
```
mixin avatar(options = {name:"name", surname:"surname", occupation:"developer"})
    -let {name="name", surname="surname", occupation="developer"} = options;
```
Твой software будет выглядеть тогда так в таком ключе:
```
mixin software(...args)
  .software
    +title('fas fa-laptop', 'SOFTWARE')
    .software__barcont
      each val in args
        +bar(val)
```
а уже bar будет разбирать объект val, делать декомпозицию и смотреть что там упало и упало ли вообще что-то и если не упало пользовать дефольные значения. Кстати тут тоже сокращения у тебя args всякие, да val

**Comment by performanceArtist** [comment]
Ну args в rest-параметрах используется повсеместно, как в случае с e в обработчике события.

**Comment by performanceArtist** [comment]
Просто тут никакой они смысловой нагрузки не несут получается - по ним ведётся итерация и они передаются дальше.

**Comment by Sergio-Ka** [comment]
Может и не несут. Но тут вопрос привычки. Привыкай делать нормально везде.
> как в случае с e в обработчике события
Ты почитай в стандартах, что по поводу `e` пишется.

**Comment by performanceArtist** [comment]
>Ты почитай в стандартах, что по поводу e пишется.

Я не нашёл ничего. Только упоминается, что использовать не this, а объект события, то есть `e`. Вот даже цитата:

>Вместо этого получать данные через объект события "e.currentTarget.value"

Хотя может и опечатка, поди лучше имя `event` использовать, чтобы было понятнее.

**Comment by Sergio-Ka** [comment]
Раньше про "е" было, сейчас тоже найти не могу. Но лучше да, писать "event".
На счет передачи параметров - вижу, есть декомпозиция. А вот проверки на то, что может объект не передаваться, а передаваться какая-то ерунда - нет. Так же нет проверки на то, если вообще ничего не передается. Выше я уже приводил пример как это делается. Компоненты должны быть хотя бы минимально устойчивыми. От куда ты знаешь, что там может прилететь в него параметром снаружи? Может кто-то ошибется и передаст скажем слово вместо объекта с параметрами? Или вообще ничего не передаст? Тут надо доделать.
![Снимок](https://user-images.githubusercontent.com/33621369/57430251-4cf08e00-7259-11e9-8ec6-d369ebb343ec.PNG)

**Comment by Sergio-Ka** [comment]
Вижу, уже по передаче параметров переделано. Но там одна проблема - можно сделать оптимальнее, короче. Один из способов я привел. Это довольно важно. Более лаконичный код легче воспринимается, занимает меньше места. Еще один вариант - вместо такого:
``` javascript
mixin avatar(options)
  -let defaults = {
  -  url:'', 
  -  name:'NAME HERE',
  -  surname:'SURNAME',
  -  occupation:'OCCUPATION'
  -}
  -let {url, name, surname, occupation} = Object.assign(defaults, options)
```
Можно сделать так:
``` javascript
mixin avatar({name="name", surname="surname", occupation="occupation"} = {})
```
Тут тебе и декомпозиция и дефолтные значения и проверка на пустой объект и проверка на то что там вообще не объект и все в одной строчке.
Тут кстати исправь сразу один момент. У тебя в circle-bar жестко зашит параметр на количество кружков - 12, а если ты захочешь сделать шкалу на 8 кружков или 20? Сделай миксин более универсальным, передавай это параметром сверху.

**Comment by performanceArtist** [comment]
Так конечно короче, но в случаях когда параметров много или их значения по умолчанию длинные, получится нечитаемо. В том же experience/education оно может даже на экран не поместиться. И pug не позволит писать параметры функции в несколько строк. Исправил пока там, где всё коротко. Что можно с другими сделать? Или можно так оставить?

**Comment by performanceArtist** [comment]
И в circle-bar было значение по умолчанию 12 у второго параметра, чтобы вручную его не вбивать каждый раз. Поменять можно.

**Comment by performanceArtist** [comment]
Хотя там оно почему-то вне объекта было - я поправил.

**Comment by Sergio-Ka** [comment]
Если много параметров можно делать так например. 
```javascript
mixin avatar(options = {})
  -let{url='', name='HERE', surname='SURNAME', occupation='OCCUPATION'} = options;
```
И применить нормальное форматирование, чтобы читаемо было. И все одно короче. experience/education можно и не делать для всех, а только для одного пункта сделать дефолтное значение, тогда не надо будет все писать. Сделаешь в info - там уже внутрянка будет смотреться конкретно по каждому.
Ну и тут кстати везде надо поправить, в смысле во всех блоках делать подобным образом.

**Comment by Sergio-Ka** [comment]
> И в circle-bar было значение по умолчанию 12 у второго параметра, чтобы вручную его не вбивать каждый раз. Поменять можно.

Это настраиваемый блок должен быть, 12 нужно передавать сверху вместе с другими параметрами иначе ты затрудняешь его переиспользование, завязывая на жестко заданное внутри значение.

**Comment by performanceArtist** [comment]
Пусть тогда будет в info подстановка значений. С circle-bar там всё можно установить и передать сейчас.

**Comment by Sergio-Ka** [comment]
По профайлу норм сейчас реализация. Только там по семантике явно подходит <p> для текста. Так как абзац. То что ты экранируешь знаком '-' это по факту js код. Ставь точку с запятой в конце выражения, как это принято. Понятно что будет и так работать, но код выглядит неряшливо. Лучше сразу вырабатывать привычку, а не так что там ставлю, тут не ставлю.
По поводу 12. Я не вижу где сейчас задается число 12 в разделе skills в файле index.pug? Я уже третий раз говорю, что это нужно передавать параметром.

**Comment by performanceArtist** [comment]
Добавил явные аргументы в вызове в index.pug. 12 по идее должно быть в объекте, который передаётся circle-bar. Раньше оно написано не было и бралось по умолчанию(`{name = 'Name', dotCount=6, length = 12} = {}`). Точки с запятыми добавил - видать, привык что редактор за меня их ставит, вот и пропустил местами.

**Comment by Sergio-Ka** [comment]
Чего-то посмотрел - не везде нормально сделано в плане проверки на дефолты и декомпозиция. В тех же education/experience осталось   -let array = options instanceof Array ? options : [{}]; В resume нет проверки на пустой объект типа mixin resume(data **= {}**) В skills sofware так же. В title кстати тоже надо сделать и проверку и декомпозицию.

**Comment by performanceArtist** [comment]
`-let array = options instanceof Array ? options : [{}];`
Это сделано чтобы не проводить итерацию по строке. Можно как-нибудь этот случай учесть с деструктуризацией?

**Comment by performanceArtist** [comment]
Короче ладно, пусть так пока будет.

**Comment by Sergio-Ka** [comment]
> `-let array = options instanceof Array ? options : [{}];`
> Это сделано чтобы не проводить итерацию по строке. Можно как-нибудь этот случай учесть с деструктуризацией?

Не понял, что значит итерация по строке? По title сделано, по остальному замечания остаются.

**Comment by performanceArtist** [comment]
>Не понял, что значит итерация по строке?

Если передать строку вместо массива с объектами, то each в pug будет по ней идти. Так как строка - массив символов.

**Comment by performanceArtist** [comment]
>По title сделано, по остальному замечания остаются.

Я везде же исправил - software, skills, так далее.

**Comment by Sergio-Ka** [comment]
И что из того? На счет того что строка это массив пожалуй не соглашусь. Это не С. Здесь строка это отдельный тип, а объекты отдельный.  Думаю так будет лучше:

```javascript
mixin education(options = {})
  section.education
    +title('fas fa-star', 'EDUCATION')
    ul.education__list
      each object in options
        +info(object) 
```

**Comment by Sergio-Ka** [comment]
Вижу сделал. ОК.
