### ISSUE TITLE
Именование классов по БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#5]
fas fa-lightbulb
Это что? Элемент? Блок? Выглядит как микс классов. По стандартам FSD миксы классов кроме миксов модификаторов не допустимы. Кроме того тут css свойства весят на селекторе элемента i. По БЭМ используются селекторы классов (исключение html, body хотя и не указано в стандартах, но все же). Само использование тэга <i> сомнительно и не понятно.

**Comment by performanceArtist** [comment]
Это иконки font-awesome, стили к ним так и подключаются - с тегом i и двумя классами - главный и побочный. Могу разве что заменить на изображения.

**Comment by Sergio-Ka** [comment]
Ну ок. Пусть остается.

**Comment by Sergio-Ka** [comment]
Нашел одну проблему.
.circle-bar__checked
.circle-bar__unchecked
Именовано как модификаторы, а написано через два нижних пробела как элементы. тут явно должно быть что-то типа
.circle-bar__dot.circle-bar__dot_checked
circle-bar__dot.circle-bar__dot_unchecked
