### ISSUE TITLE
Вернемся к БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#7]
БЭМ на самом деле реально крутая методология. Но в ней есть некоторые тонкости которые нужно понять. Кроме того стандарты FSD явно указывают на некоторые моменты, которые ей не соответствуют. Например миксы не допустимы (кроме миксов модификаторов), позиционирование через внешние div (или иные) блоки для которых и задается сбственно позиционирование. Это преамбула.
Теперь конкретно. Когда я вижу что-то вроде:
.content
      .row
          .left
у меня возникает вопрос, а хорошо ли человек разобрался с БЭМом? Как нужно это переделать так чтобы по БЭМ было корректно? Дам подсказку - можно использовать элементы и модификаторы.

**Comment by performanceArtist** [comment]
Я просто там не сделал, потому что это самый "внешний" уровень. По БЭМ было бы нечто вроде этого:
```.content content_equal
  .content__left
  .content_right`

**Comment by performanceArtist** [comment]
Я просто там не сделал, потому что это самый "внешний" уровень. По БЭМ было бы нечто вроде этого(без логики миксинов, модификаторы можно аргументами добавить):
```pug
div(className = '.content .content_equal-width')
  .content__left
  .content__right
```

**Comment by performanceArtist** [comment]
Я просто там не сделал, потому что это самый "внешний" уровень. По БЭМ было бы нечто вроде этого(без логики миксинов, модификаторы можно аргументами добавить):
```pug
div(class = '.row .row_equal-width')
  .row__left
  .row__right
```

**Comment by performanceArtist** [comment]
Или я чего-то не понял? Такой блок было бы неудобно в pug делать, т.к. там внутри миксина нельзя задать несколько блоков с именами, в отличие от отдельного файла. Если только не положить туда большую часть контента и принимать сразу кучу переменных.

**Comment by performanceArtist** [comment]
Хотя если делать интерфейс для генерации, там может быть удобно сразу все данные из формы взять в виде одного объекта, тогда можно сделать нечто подобное(псевдокод):
```pug
mixin resume(data, style ='default')
  -let{avatar, education} = data
  div(class = `.resume .resume_${style}`)
    .resume__left  
      +avatar(avatar)
    .resume__right
      +education(education)
```

**Comment by Sergio-Ka** [comment]
Я бы сделал например так:
```
.content
      .content__row.content__row_position_left
      .content__row.content__row_position_right
```
Это что до БЭМа. Ну и поскольку у нас компонентный подход и я говорил о том, что каждый блок - это миксин, то блок content в данном случае тоже бы стал миксином и переехал в отдельную папку. В него бы передавался массив объектов, то есть [{}, {}, {} ....] где каждый объект - это блок (точнее его настройки) по бэм так же оформленный миксином, в каждом таком блоке вызывается свой миксин и так далее. Плюс такого подхода - мы в одно место даем параметры, а данные внутри распределяются за счет того, что при подключении миксинов в миксинах образуется древовидная структура. Тебе не надо будет ходить в каждый отдельно взятый миксин, если у тебя поменяются отдельные данные или все вместе (заголовки, тексты, картинки и т.д.). Ты задал это в одном месте в корне (в корневом миксине), а оно распределилось дальше само.

**Comment by Sergio-Ka** [comment]
Да, до кучи еще поясню почему стоит передавать именно массив объектов, а не просто передавать массивы в виде параметров. Возьмем блок software. Сейчас там 6 шкал. А если 100 будет? Внутри блока должен быть итеративный механизм, который будет ходить по всему массиву объектов и который будет обеспечивать логику формирования этих шкал в зависимости от их количества. Ты ему 100 на вход подаешь - он 100 блоков оформляет, 1000 - значит 1000. Не ты внутри миксины bar вручную вызываешь, а миксин software вызывает их сам в зависимости от того сколько объектов в массиве который подан ему на вход. Такая же тема со skills.

**Comment by performanceArtist** [comment]
>Не ты внутри миксины bar вручную вызываешь

Так там так и сделано. Я говорил только про сам bar. Конечно в software/skills итерация есть.

**Comment by Sergio-Ka** [comment]
В принципе я это уже писал в другом ишью и у тебя глянул еще раз реализовано вроде как даже, да. Но вопрос про контент остается.

**Comment by performanceArtist** [comment]
А, так контент тоже изменить?

**Comment by Sergio-Ka** [comment]
Да. content изменить.

**Comment by Sergio-Ka** [comment]
```
.resume
    .resume__left
    .resume__right
```
Это не элементы left и right блока resume ,это колонки должны быть у блока resume. А левые они или правые задается модификатором. То есть типа .resume__column.resume__column_position_left

**Comment by performanceArtist** [comment]
Да, ступил что-то. Надо же чтобы название описывало **что** это, не **какое** оно.
