### ISSUE TITLE
Выложить изображение для perfectpixel

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/resume_template#8]
Можно в проект добавить в корень. И настройки perfectpixel желательно, на которых версталось. Можно сюда комментом.

**Comment by performanceArtist** [comment]
Здесь нельзя картинки прикреплять, как я понял, положил в корень: [cv](https://github.com/performanceArtist/resume_template/blob/master/cv.jpg) Масштаб 35%(да, надо было больше - у меня экран маловат, сразу не подумал). Ещё посмотрел сейчас - там что-то съехало. Упомяну, когда подгоню получше.

**Comment by Sergio-Ka** [comment]
В принципе норм с учетом кривости макетов, разницы в экранах и того что шрифты в макете платные. Но у меня почему-то в блоке software шкалы отображаются не корректно.
![Снимок](https://user-images.githubusercontent.com/33621369/57007621-3a9ca180-6c14-11e9-984f-f56084ed92bc.PNG)

**Comment by performanceArtist** [comment]
Там название переменной было неправильное. В общем я всё равно поближе подогнал.

**Comment by Sergio-Ka** [comment]
В принципе нормально. Не буду новое ишью по респонсив формировать задам здесь.
1. skills как-то не очень здесь выглядит, как полагаешь?
![Снимок](https://user-images.githubusercontent.com/33621369/57008663-c6fe9280-6c1b-11e9-92f2-d4d01469ac35.PNG)
2. Думаю, стоит рассмотреть выстаивание блока software в одну колонку при узком экране.

**Comment by performanceArtist** [comment]
Там всё выстраивается в одну колонку, но наверное значение можно побольше задать(сейчас 900px).

**Comment by performanceArtist** [comment]
Сделаю пожалуй изменение размеров/отступов для точки в skills и брейкпоинт для software, а то 900px - и так много.

**Comment by performanceArtist** [comment]
В итоге сделал пока так: при незначительном увеличении изменяется ширина всего резюме, далее при меньшем размере все части выстраиваются в одну колонку. При ещё большем уменьшении в блоке skills полоски выстраиваются в одну колонку. На мой взгляд всё меняется нормально, вид элементов сохраняется. Software решил не выстраивать, т.к. он не "ломается" даже при размере в 200-300px, в отличие от skills.

**Comment by Sergio-Ka** [comment]
Ну мне в принципе кажется, что выглядит не плохо в целом.

**Comment by Sergio-Ka** [comment]
Посмотрел еще один момент. Часть текста в profile должна быть выделена жирным шрифтом. Там на макете видно. Это сделано не просто так. Нужно доделать.

**Comment by performanceArtist** [comment]
Добавил пока обычным html. Так пойдёт?

**Comment by performanceArtist** [comment]
Раньше был вариант с block в pug, но теперь там всё передаётся в объекте и так сделать не получится.

**Comment by Sergio-Ka** [comment]
Нет не пойдет. Там смысл был в компонентности. Компонент - черный ящик. У него есть интерфейс, через который происходит взаимодействие с ним. Как сам компонент устроен внутри не интересно тем сущностям, которые его используют. Ты передаешь параметры типа {text: 'бла-бла-бла', markedText:'например жирное бла-бла-бла'}, а как там компонент действует внутри и что будет делать с переданными параметрами - интересно только самому компонету и его разработчику. Это по сути и есть инкапсуляция. Все эти миксины для блоков (компонент) - это необходимость научить стажеров мыслить в понятиях компонент. У тебя есть компонент, изменяемые части которого выносятся в параметры. Так вот если подумать в этом ключе над блоком профайл - у тебя сейчас один текст жирным выделен, а завтра к нему добавятся 2 буквы, а послезавтра еще 3. Каждый раз будешь лезть в код и править вручную? Что мешает сделать что-то типа такого:
```javascript
p.profile__content= text
            span.profile__significant-content= textMarked
```

**Comment by performanceArtist** [comment]
Сделал. Дело в том, что такой способ для реального форматирования не подойдёт, потому и были сомнения. Не выделять же каждый жирный текст, ссылку или подобное как параметр - может, их там штук десять и все в разных местах. Если это для демонстрации компонентного подхода, то ок.

**Comment by Sergio-Ka** [comment]
Скорее да, тут учебный случай.
