### ISSUE TITLE
Автоматический импорт стилей

### ISSUE THREAD

**Issue by Sha1fei** [performanceArtist/resume_template#9]
Сделать импорт автоматическим в app.js чтобы не приходилось какие стили добавлены, а какие забыл.

**Comment by Sergio-Ka** [comment]
Ты тут как-то наполовину сделал. Сделай вообще для всех стилевых файлов в пределах папки src, чтобы в ручную не приходилось тебе эти импорты писать, чтобы скрипт сам ходил по папкам и все эти вещи подтягивал. Там до кучи можно еще и картинки так же в этом же месте собирать. Через регулярку что-то типа /\.(scss|css|png|jpg)$/ ну и так далее.

**Comment by performanceArtist** [comment]
Ок, пусть весь css собирает.

**Comment by Sergio-Ka** [comment]
Не понял, а зачем там в функции так '../src' вместо просто './'?

**Comment by performanceArtist** [comment]
Потому что сам app.js в src лежит. './' - это уже относительно src, внутри него.

**Comment by performanceArtist** [comment]
Хотя понял, можно и просто './'.

**Comment by Sergio-Ka** [comment]
Можно закрыть это issue.
